server:
  port: 8100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjlee9541/git-config-test
          cloneOnStart: true
          searchPaths: 'resource/config/{application}'
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true